// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR-qUvfv0w8dldHxmcvEhFJZJ_rnM8SNE',
    appId: '1:772856837706:web:d7a0c76e527e025a0b18b3',
    messagingSenderId: '772856837706',
    projectId: 'legallens-2c844',
    authDomain: 'legallens-2c844.firebaseapp.com',
    storageBucket: 'legallens-2c844.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwztg3v2i2_3pK73hyXAB0rVoTtGIdtGc',
    appId: '1:772856837706:android:3ecd12c14dc51f1c0b18b3',
    messagingSenderId: '772856837706',
    projectId: 'legallens-2c844',
    storageBucket: 'legallens-2c844.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdmm_X5RHZ418tD7hCKXUKmpSbr785G9Y',
    appId: '1:772856837706:ios:2022a37aa0daec910b18b3',
    messagingSenderId: '772856837706',
    projectId: 'legallens-2c844',
    storageBucket: 'legallens-2c844.firebasestorage.app',
    iosBundleId: 'com.example.legallens',
  );
}
